# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/melius-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter meliusltexx,$(TARGET_DEVICE)),)

endif
